### ISSUE TITLE
How to calculate NDVI from Sentinel-2 to any AOI with coordinates based on python API

### ISSUE THREAD

**Issue by Elbossily** [sentinel-hub/custom-scripts#170]
How to calculate NDVI from Sentinel-2 to any AOI with coordinates based on python API

**Comment by batic** [comment]
Hi @Elbossily,

Please have a look at [sentinelhub-py](https://sentinelhub-py.readthedocs.io/en/latest/) library, specifically [FIS request](https://sentinelhub-py.readthedocs.io/en/latest/examples/fis_request.html#).
