### ISSUE TITLE
Why is the LAI output divided by 3

### ISSUE THREAD

**Issue by SOWITMA** [sentinel-hub/custom-scripts#176]
Hello,

Looking at the code I was wondering what was the rational of divided the LAI output by 3 ?

 var lai = denormalize(l2, 0.000319182538301, 14.4675094548151);
  return {
    default: [lai / 3]
  }

Thanks for your input,
Best
HB

**Comment by MonjaSebela** [comment]
Dear HB, 

I believe the output is divided by 3 to decrease the brightness of the output and thus display more visual information. If you  remove the division from the script, you will see the result to be a bit too bright with much less visual information. Multiplying with larger or lower values is a common practice in custom scripts. We often multiply the bands in true color composites with 2.5 to increase the brightness, and here, dividing with 3 is the same as multiplying with 0.3333333, which will decrease the gain of the final output. 

Best, 
Monja

**Comment by SOWITMA** [comment]
Thanks for your detailed answer.

Best Regards,
HB
