### ISSUE TITLE
Log scale

### ISSUE THREAD

**Issue by geom16011** [sentinel-hub/custom-scripts#2]
Is there any function that i could use to visualize my values with colours in logarithmic scale?

**Comment by mkadunc** [comment]
You could try something like this:
```
   const min = 0.001;
   const max = 5;
   return [(Math.log(B04) - Math.log(min))/(Math.log(max) - Math.log(min))];
```

**Comment by geom16011** [comment]
Thanks for your  answer.
for example i calculate this value
var R_443_560=B01/B03
var R_490_560=B02/B03
var MBR=Math.log10(Math.max(R_443_560,R_490_560))
var NDWI=(B03-B08)/(B03+B08)  
var Med=Math.pow(10,(0.283-2.753*MBR+1.457*MBR**2+0.659*MBR**3-1.403*MBR**4))

And i want to show the values of Med with a logarithmic scale (however not cahnging the original values as caclulated from  the script). Any ideas?

**Comment by mkadunc** [comment]
You could just use the expression from argument of `Math.pow` in the visualizer (since `log` is inverse of `pow`).

```
const R_443_560 = B01/B03;
const R_490_560 = B02/B03;
const MBR = Math.log10(Math.max(R_443_560,R_490_560));
const NDWI = (B03-B08)/(B03+B08);
const logMed =   0.283
               - 2.753 * MBR
               + 1.457 * Math.pow(MBR,2) 
               + 0.659 * Math.pow(MBR,3)
               - 1.403 * Math.pow(MBR,4);

const minLog = Math.log10(0.01);
const maxLog = Math.log10(5);

return colorBlend(logMed,
                  [minLog, maxLog],
                  [[0, 0.5, 0], // dark green - minimum
                   [1,1,1]]); // white - maximum
```
