### ISSUE TITLE
Question about directly using LAI calculation codes in GEE

### ISSUE THREAD

**Issue by az16735** [sentinel-hub/custom-scripts#223]
Hi there,

It is great to see the shared codes on LAI calculation using Sentinel-2 images. I want to run the script in GEE to calculate the LAI actually, but was wondering about which Sentinel-2 sensor the weights and bias in your codes fit as the algorithm handbook reads different neural networks were deployed for S2A and S2B respectively.

Many thanks,
Alex

**Comment by jonasViehweger** [comment]
Hi Alex, unfortunately we are not equipped to answer that question.
