### ISSUE TITLE
Add breadcrumbs to script pages

### ISSUE THREAD

**Issue by dderanja** [sentinel-hub/custom-scripts#264]
Accessing the scripts through search (or direct links) presents the user with a page without a clear information on what satellite data the script uses. Sometimes it is written in the description, but that's not so straightforward and the information is sometimes missing altogether. Using a script with the wrong satellite data collection will result in errors.

I'd suggest to add breadcrumbs to the individual script pages right on the top of the page, so a user always knows to which source the script applies.

**Comment by jonasViehweger** [comment]
Hello @dderanja, thanks for the feedback. I agree that it is not optimal at the moment and accessing evalscripts throught the search can make it non obvious for which sensor the script is. I will see how this can be implemented

**Comment by jonasViehweger** [comment]
Just a note: in the url you can always see which category the script belongs too. But I agree that it should be more obvious than that

**Comment by dderanja** [comment]
Thank you @jonasViehweger, looks good :+1:
