### ISSUE TITLE
Chlorophyll Red-Edge on Sentinel Hub - correct equation

### ISSUE THREAD

**Issue by NelaJantol** [sentinel-hub/custom-scripts#277]
I noticed that on the Sentinel Hub custom scripts page which is used in EO Browser and Sentinel Playground, for Chlorophyll Red-Edge the equation is not the correct one. It states:

General formula: ([760:800]/[690:720])^(-1), and the custom script also uses the equation with mathematical power (if the power was indeed -1, it would be just the inverse equation). 

The correct formula should be (B07 / B05) -1, ie like in this paper: 
(https://www.mdpi.com/2072-4292/13/14/2732)

**Comment by jonasViehweger** [comment]
Hey, thanks for catching that. This seems to be coming from a wrong entry on indexdatabase.de.

We'll change that.

**Comment by jonasViehweger** [comment]
If you notice any other mistakes like that please notify us!

**Comment by NelaJantol** [comment]
> If you notice any other mistakes like that please notify us!
Thank you for the quick response and a solution
