### ISSUE TITLE
How to mask the cyan (flooded urban area) using the sentinel-1/flood_mapping script

### ISSUE THREAD

**Issue by Jiangchao3** [sentinel-hub/custom-scripts#325]
Hi @jonasViehweger or other developers,

Could you please give me help to mask the cyan (flooded urban area) in using the script of S1 flood detection ?
https://custom-scripts.sentinel-hub.com/custom-scripts/sentinel-1/flood_mapping/

The code only give a script for masking the red pixel with a threshold of 0.05, but I am very interested in the cyan (potentienl flooded urban area), want to know how to mask it?

 // ************************************
 // mask creation
 // var dout = outbe - outdu;    
 // return [dout > 0.05 ?  1 : 0]
 // ************************************

I am a freshmen in using sentinelhub and have no idea about how to adress it, hope can get your help, many thanks!

Jiangchao

**Comment by jonasViehweger** [comment]
Hello @Jiangchao3 ,

cyan colors are characterised by high values during the flood, but low values before the flood. So you can use something like this to mask out those values: `return [(outdu > 0.3 & outbe < 0.1) ?  1 : 0]`

**Comment by Jiangchao3** [comment]
Hi @jonasViehweger,

Thank you very much for your kind reply. I tried your code, but it seems not generate result that I expect, I put my result and code here, and looking forward to your suggestion.

I have two image, before flood is 2023-03-31, during flood is 2023-04-12,

When I use for the output, it's Figure 1
When I use for the output, it's Figure 2

**Figure 1**: 
![vv_0412_0331](https://github.com/user-attachments/assets/2d77f885-a6c5-4a2e-9b53-6b6649ba639b)

**Figure 2**
![vv_0412_0331_cyan](https://github.com/user-attachments/assets/24874d8a-6098-4b87-8e9e-8382b2f10229)

**Comment by jonasViehweger** [comment]
You will have to play with the thresholds. Some of those cyans are also almost white, if you want to get white areas you need to delete the `& outbe < 0.1` part.

**Comment by Jiangchao3** [comment]
Thanks @jonasViehweger, it works.
