### ISSUE TITLE
NBR formula

### ISSUE THREAD

**Issue by madi** [sentinel-hub/custom-scripts#8]
According to the reference [page](https://www.indexdatabase.de/db/si-single.php?sensor_id=96&rsindex_id=53) reported in the script, the bands that should be used for this index are 9 and 12, not 8 and 12.

**Comment by hareldunn** [comment]
I presume it's referring to the MSI band by their order, not by name, thus is actually listing bands 8A and 11 of the MSI, which also have the same 20 meter resolution.

**Comment by gmilcinski** [comment]
Indeed. They present their order here:
https://www.indexdatabase.de/db/bs.php?sensor_id=96

**Comment by madi** [comment]
Thanks for the clarification. 
Regards,
