### ISSUE TITLE
Multi-temporal Data isuue

### ISSUE THREAD

**Issue by Narayana-Rao** [sentinel-hub/custom-scripts#95]
Hi,
I am unable to run the script (sar_multi-temporal_backscatter_coefficient_composite) in EO browser custom scipt.
can please you help me in this?
I think there is issue with temporal data. 
Thank you!

**Comment by zigacernigoj** [comment]
Hey,
EO Browser doesn't support multitemporal processing.

Please try running the script in the [multitemporal instance of Sentinel Playground](https://apps.sentinel-hub.com/sentinel-playground-temporal/?temporal=true) and report if the issue still persists or if a new issue appears.

Best of luck!

**Comment by Narayana-Rao** [comment]
Thank you very much!!
It's working in Sentinel playground.
